/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconSearch: typeof import('./src/components/IconSearch.vue')['default']
    IconSlot: typeof import('./src/components/IconSlot.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SidebarListItem: typeof import('./src/components/SidebarListItem.vue')['default']
  }
}
